##########################################################
# Title: Donut Diagram
# Suggestion from Dr. Nawwaf Kharma - Concordia University
#
# Author: Vincent Beaulieu
# Date: 14 September 2022
###########################################################
###########################################################
#
# Info: Display in a circular diagram the folding 
# probabilities of a RNA sequence using a coolwarm colormap
#
###########################################################

# (dark red (G) and dark blue  (C), and light green (A) and light yellow (U))
# from max thickness of about ~1 mm for ~ 1 prob., to non-existent prob. for anything with too low pairing probability)

import networkx as nx
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

from ML.py_files import toolbox

G = nx.Graph()





sequence_nb = 1000

# Get data from ".prob" file (Generated by VARNA)
filepath = 'Datasets/HDV/prob/SEQUENCE_'+str(sequence_nb)+'.prob'
data = toolbox.csv_reader(filepath,delimiter='\t')

# Convert data from string to float
prob_data = np.array(data).astype(float)

# Extract data and create nodes and edges
edge_stack=[]
color_stack=[]
max_prob = 0
min_prob = 1
for i in range(prob_data.shape[0]): # row
    for j in range(prob_data.shape[1]): # col
        tmp_prob = prob_data[i,j]
        # print(i,j,tmp_prob); if i == 3: exit()
        if tmp_prob > 0:
            if tmp_prob > max_prob: max_prob = tmp_prob
            if tmp_prob < min_prob: min_prob = tmp_prob
        G.add_edge(i,j)
        edge_stack.append(tmp_prob)
        pass
    pass

# Set background color
plt.style.use('dark_background')
fig, ax = plt.subplots()

# Choose colormap ref: https://matplotlib.org/stable/tutorials/colors/colormaps.html
cmap = plt.cm.coolwarm

# Get the colormap colors
my_cmap = cmap(np.arange(cmap.N))

# Set alpha (transparency)
my_cmap[:,-1] = np.linspace(0, 1, cmap.N)

# Create new colormap
my_cmap = mpl.colors.ListedColormap(my_cmap)

# Normalize and assign the new color map with the ".prob" data
norm = mpl.colors.Normalize(vmin=min_prob, vmax=max_prob)
m = mpl.cm.ScalarMappable(norm=norm, cmap=my_cmap)
for e in edge_stack:
    color_stack.append(m.to_rgba(e))

# Define labels and nodes color
filepath = 'Datasets/HDV/fasta/single/SEQUENCE_'+str(sequence_nb)+'.fasta'
data = toolbox.csv_reader(filepath,delimiter='\n')
labeldict = {}
colordict = []
tmp = list(data[1][0])
for i in range(len(G.nodes)):
    labeldict[i] = tmp[i]
    if tmp[i] == 'G':
        colordict.append('r')
    elif tmp[i] == 'C':
        colordict.append('b')
    elif tmp[i] == 'A':
        colordict.append('#90EE90') # light green
    else:
        colordict.append('#FFFFE0') # light yellow

# Define the layout
pos = nx.circular_layout(G)
options = {
    "node_size"  : 100,
    "node_color" : colordict,

    "font_size"   : 8,
    "with_labels" : True,
    "labels"      : labeldict,
    "font_color"  : "k",

    "edge_color" : color_stack,
    "width"      : 1,
}

nx.draw_networkx(G, pos, **options)



#for node, (x, y) in pos.items():
#   plt.text(x, y, node, color=fontdict[node], label=labeldict[node] , ha='center', va='center')

# Display the diagram
plt.gca().margins(0)
plt.tight_layout()
plt.axis("off")
plt.show()