import os
import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

# TODO: create setup.py and venv to simplify import
try:
    from data_properties import HDV_LIG14
except:
    try:
        print("\033[93m" + "**WARNING** Relative Import Failed - Trying Absolute Import")
        
        import sys

        parentdir = os.path.dirname(currentdir)
        sys.path.insert(0, parentdir)

        from data_properties import HDV_LIG14
        print("\033[32m" + "**MESSAGE** Import Process Completed")
    except:
        print("\033[91m" + "**ERROR** Import Process Failed")
finally:
    print("\033[0m")


# Position Extractor
def position_extractor():
    LIG_Lib14_RNA = HDV_LIG14.lig_rna_sequence
    HDV_Lib14_RNA = HDV_LIG14.hdv_rna_sequence

    # Find in consecutive order the position of all IUPAC nonsingleton nucleotide set
    def get_nt_position(rna_type):
        i = 0
        p = 0
        nt_pos = []
        for s in rna_type:
            if s != 'A' and (s != 'T' and s!='U') and s != 'C' and s != 'G':
                i += 1
                nt_pos.append([i,s,p])
            p += 1
        return nt_pos
    # ref: https://www.bioinformatics.org/sms/iupac.html
    
    
    description = "* Results generated by the position_extractor function in data.py"

    hdv_list_title = "HDV IUPAC nucleotides positions:"
    hdv_nt_pos = get_nt_position(HDV_Lib14_RNA)

    lig_list_title = "LIG IUPAC nucleotides positions:"
    lig_nt_pos = get_nt_position(LIG_Lib14_RNA)

    temp_warning = "* There might be an error in the provided assignment guides about the RED letters."

    filepath = currentdir + "/" + "nt_position.txt"
    print(filepath)
    with open(filepath,'w') as file:
        file.write("%s\n" % description)
        
        file.write("\n%s\n" % hdv_list_title)
        for item in hdv_nt_pos:
            i,s,p = item
            file.write("%i\t%c\t%i\n" % (i,s,p))

        file.write("\n%s\n" % lig_list_title)
        for item in lig_nt_pos:
            i,s,p = item
            file.write("%i\t%c\t%i\n" % (i,s,p))

        file.write("\n%s\n" % temp_warning)

    # See 'nt_position.txt'

if __name__ == '__main__':
    # test()
    position_extractor()
    pass

